# FROM node:14

# RUN mkdir -p /app

# WORKDIR /app

# COPY package*.json /app/
# COPY yarn.lock /app/

# RUN npm install

# COPY . /app

# # RUN npm run build

# EXPOSE 80
# EXPOSE 3000
# EXPOSE 49153

# CMD ["npm", "run", "dev"]
